janjagruti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("schemes.urls")),
    path("", include("editor.urls")),
    path("", include("profiles.urls")),
    path("", include("news.urls")),
    path("", include("recommendation.urls")),
]

admin.site.site_header = "Admin"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to Admin Portal"
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import (
    NewsListView,
    NewsDetailView)
urlpatterns = [
    path('news/',NewsListView.as_view(),name="news"),
    path('news/<slug:slug>/',NewsDetailView.as_view(), name='newsdetail' )
    # path('news/login/', CustomLoginView.as_view(), name='login'),
    ]

recommendation/urls.py
from django.urls import path
from .views import usersList, details

urlpatterns = [
    path('editor/email/', usersList.as_view(), name='email'),
    path('editor/users/<int:id>',details, name = "up")
]

profiles/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from schemes.models import State


# # Create your models here.
class Profile(models.Model):
    # name = models.CharField(max_length=1)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('T','Transgender')
    )
    MARTIAL_STATUS=(
        ('M','Married'),
        ('U','Unmarried'),
        ('D','Divorced'),
        ('W','Widowed')
    )
    RESIDENCE_AREA = (('U','Urban'),('R','Rural'))
    CASTE = (
        ('Gen','General'),
        ('OBC','Other Backward Class (OBC)'),
        ('PVTG','Particularly Vulnerable Tribal Group (PVTG)'),
        ('SC','Scheduled Caste (SC)'),
        ('ST','Scheduled Tribe (ST)')
    )
    EMPLOYEMENT = (
        ("Employed","Employed"),
        ('Unemployed','Unemployed'),
        ('Enterpreneur','Enterpreneur')
        )
    BOOLEAN_VALUE = (('T','True'),('F', 'False'))
    # state_choices = (("Andhra Pradesh","Andhra Pradesh"),("Arunachal Pradesh ","Arunachal Pradesh "),("Assam","Assam"),("Bihar","Bihar"),("Chhattisgarh","Chhattisgarh"),("Goa","Goa"),("Gujarat","Gujarat"),("Haryana","Haryana"),("Himachal Pradesh","Himachal Pradesh"),("Jammu and Kashmir ","Jammu and Kashmir "),("Jharkhand","Jharkhand"),("Karnataka","Karnataka"),("Kerala","Kerala"),("Madhya Pradesh","Madhya Pradesh"),("Maharashtra","Maharashtra"),("Manipur","Manipur"),("Meghalaya","Meghalaya"),("Mizoram","Mizoram"),("Nagaland","Nagaland"),("Odisha","Odisha"),("Punjab","Punjab"),("Rajasthan","Rajasthan"),("Sikkim","Sikkim"),("Tamil Nadu","Tamil Nadu"),("Telangana","Telangana"),("Tripura","Tripura"),("Uttar Pradesh","Uttar Pradesh"),("Uttarakhand","Uttarakhand"),("West Bengal","West Bengal"),("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),("Chandigarh","Chandigarh"),("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),("Daman and Diu","Daman and Diu"),("Lakshadweep","Lakshadweep"),("Delhi","Delhi"),("Puducherry","Puducherry"))
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES ,default= 'Female')
    age = models.IntegerField(default=1,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ])
    martial_status = models.CharField(max_length=10, choices=MARTIAL_STATUS)
    state = models.ForeignKey(State,on_delete=models.CASCADE,default = 1)
    area_of_residence = models.CharField(max_length=1, choices=RESIDENCE_AREA)
    caste = models.CharField(max_length = 4, choices = CASTE)
    disable = models.CharField(max_length=1, choices=BOOLEAN_VALUE, default= 'True')
    student = models.CharField(max_length=1, choices=BOOLEAN_VALUE, default= 'True')
    bpl = models.CharField(max_length=1, choices=BOOLEAN_VALUE, default= 'True')
    income = models.DecimalField(max_digits=9, decimal_places=2)
    employement = models.CharField(max_length=15, choices=EMPLOYEMENT, default= 'True')
    email = models.EmailField(default = "")
    is_current = models.BooleanField(default=True)
    def __str__(self) -> str:
        return f"{self.email}"

    def save(self, *args, **kwargs):
        Profile.objects.filter(email = self.email,is_current = True).update(is_current = False)
        super(Profile, self).save(*args, **kwargs)
        

recommendation/models.py
from django.db import models
from django.utils import timezone
from schemes.models import Schemes
from profiles.models import Profile
# Create your models here.

class RecommendScheme(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE,limit_choices_to={"is_current": True})
    scheme = models.ForeignKey(Schemes, on_delete=models.CASCADE)
    recommendDate = models.DateTimeField(default=timezone.now)
    
    def __str__(self) -> str:
        return f"{self.user} - {self.scheme}"
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'scheme'], 
                name='unique recommendation'
            )
        ]

recommendation/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
# from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
# from bs4 import BeautifulSoup
import codecs
from .email import send_emails
# from django.core.mail import 
import os
from profiles.models import Profile
from django.views.generic import (
  View
)
from django.contrib.auth.mixins import LoginRequiredMixin
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
# print(ssl.get_default_verify_paths())
class usersList(LoginRequiredMixin,View):

    def get(self,request):
        # users= get_user_model().objects.all()
        users  = Profile.objects.filter(is_current = True)
        context = {
            'users':users
        }
        print(users)
        return render(request=request, template_name='usersList.html',context=context)

    def post(self,request,*args,**kwargs):
        # HTMLFile = open("/Users/sandeepsuthar/Desktop/project/exampleapp/sendmail/design-template.html", "r")
        # print(form.cleaned_data['my_form_field_name'])
        # print(request.POST)
        # codecs.open("")
        # Reading the file

        # to_emails = [
        #     ('sandeepparmar9467@gmail.com', 'Sandeep Suthar'),
        #    
        # ]
        if request.method == 'POST':
            
            # print('v',request.POST.get('message'), request.POST.get('isCustomMessage')=='true')
            users_ids = request.POST.getlist('ids[]')
            # print(users_ids)
            # list = get_user_model().objects.get(id=users_ids)
            # print(list)
            # response = sendgrid_client.send(message)
            # print(response.status_code)
            # print(response.body)
            # print(response.headers)
            if request.POST.get('isCustomMessage')=='true':
                send_emails(users_ids, messageContent=request.POST.get('message'), isCustomMessage=True)
            else:
                send_emails(users_ids)
            
            return redirect('email')
        
def details(request, id=None):
    print(id)
    instance = get_object_or_404(Profile, id=id)
    context={
        'instance': instance
    }
    return render(request, 'modal.html', context)

recommendation/templates/modal.html
<div class="modal fade" id="myEdit" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">User Profile</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <label><b>Email Id: </b></label> <span class = "">{{instance.email }}</span><br>
                <label><b>Gender: </b></label> <span class = "">{{instance.get_gender_display }}</span><br>
                <label><b>Martial Status: </b></label> <span class = "">{{instance.get_martial_status_display }}</span><br>
                <label><b>State: </b></label> <span class = "">{{instance.state.name }}</span><br>
                <label><b>Caste: </b></label> <span class = "">{{instance.get_caste_display }}</span><br>
            </div>
            <div class="modal-footer">
                <button  value="" type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
  </div>

recommendation/templates/usersList.html
{% extends "editor/base.html" %}
{% block content %}
        <div class="row d-flex">
            <div class="col-md-4">
                <div class="row">
                   
                    <div class="col-md-6 mb-2 p-0">
                        <button type="button" class="btn btn-primary send-mail btn-sm" disabled="disabled"> <i class="fa fa-share"></i> Send Mail</button>
                    </div>
                    <div class="col-md-6 success-mail p-0" style="display: none;">
                        <div class="alert p-2 alert-success m-0">
                          Mail Sent Successfully.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th><input type="checkbox" value="1" name="user-all" class="user-all"></th>
                                {% comment %} <th>Name</th> {% endcomment %}
                                <th>UserEmail</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% csrf_token %}
                            {% for user in users %}
                            <tr>
                                <td><input type="checkbox" name="ckeck_user[]" class="ckeck_user" value="{{ user.id }}"></td>
                                {% comment %} <td>{{ user.username}}</td> {% endcomment %}
                                <td><a class="open-modal" data-url="{% url 'up' id=user.id %}">{{ user.email }}<i class='ti-link'></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div id="modal-div"></div>
            </div>
            <div class="col-md-8">
                <div>
                    <div class="form-check">
                        <input class='form-check-input' type = "checkbox" name = "isCustomMessage" id="isCustomMessage"><label class="form-check-label" for = 'isCustomMessage'>CustomMessage</label><br>
                    </div>
                    <textarea class= 'form-control input-disabled' name='messageContent' id='messageContent' disabled="disabled" placeholder = 'Enter the custom message to be send'></textarea>
                </div>
            </div>
        </div>
    <script>
        
    $('.user-all').change(function (e) {
        var value = $('.user-all:checked').val();
        if (value == 1) {
            $('.ckeck_user').prop('checked',true);
            $('.send-mail').removeAttr('disabled');
        }else{
            $('.ckeck_user').prop('checked',false);
            $('.send-mail').attr('disabled','disabled');
        }
    });  

    $(".ckeck_user").change(function () {
        if ($(".ckeck_user:checked").length > 0) {
          $('.send-mail').removeAttr('disabled');
        }else{
         $('.send-mail').attr('disabled','disabled');
       }
     });

    $('.send-mail').click(function (e) {
        e.preventDefault();
        var ids = [];
        var token = $('input[name="csrfmiddlewaretoken"]').val();
        var message = $('textarea[name="messageContent"]').val();
        if (message.lenght==0){
            return;
        }

        console.log(message);
        $('.ckeck_user:checked').each(function(i){
            ids[i] = $(this).val();
        })

        if (ids != '') {
            $(this).attr("disabled", true);
            $(this).html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Sending..');
            $.ajax({
                url: '{% url "email" %}',
                type: 'POST',
                data: {
                    ids:ids,
                    isCustomMessage:$("#isCustomMessage").is(":checked"),
                    message:message,
                    csrfmiddlewaretoken: token,
                },
                success: function (data) {
                    $('.success-mail').css('display','block');
                    $('.ckeck_user, .user-all').prop('checked',false);
                    setTimeout(function () {
                        $('.success-mail').css('display','none');
                    }, 2500)
                    $('.send-mail').html('Send Mail');
                }
            });
        }
    });
    var modalDiv = $("#modal-div");

    $(".open-modal").on("click", function() {
    $.ajax({
        url: $(this).attr("data-url"),
        success: function(data) {
        modalDiv.html(data);
        $("#myEdit").modal();
        }
    });
    });
    $("#isCustomMessage").change(function () {
        if ($("#isCustomMessage:checked").length ) {
          $('#messageContent').removeAttr('disabled');
          $('#messageContent').removeClass('input-disabled');
        }else{
         $('#messageContent').attr('disabled','disabled');
         $('#messageContent').addClass('input-disabled');
       }
    });
</script>
<style>
    .input-disabled{
        background-color:#36353545 !important;
        text-decoration: line-through;
    }
</style>
{% endblock content%}